
# resolver: lts-3.5
# resolver:
#  name: custom-snapshot
#  location: "./custom-snapshot.yaml"
resolver: lts-7.14

# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai

packages:
- '.'
- location:
    git: https://github.com/chances/servant-spotify.git
    commit: 0d7307bd
  extra-dep: true

extra-deps:
- http-client-0.5.4
- http-client-tls-0.3.3
- persistent-2.2.4.1
- persistent-postgresql-2.2.2
- persistent-template-2.1.8.1
- random-strings-0.1.1.0
- serversession-backend-persistent-1.0.2
- servant-spotify-0.2.0.2

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
